version: "3.7"
services:

  wordpress:
    image: wordpress:latest
    ports:
      - "9000:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wpwp
    # env_file: .env

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_RANDOM_ROOT_PASSWORD: true
      # MYSQL_DATABASE: wordpress
      # MYSQL_USER: wp_user
      # MYSQL_PASSWORD: hogehoge
    # env_file: .env
    # volumes:
    #     - db-data:/var/lib/mysql
