version: "3.7"
services:

  wordpress:
    image: wordpress:latest
    ports:
      - "9000:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: hogehoge
      WORDPRESS_DB_NAME: wpwp
    # env_file: .env
    networks:
      - wordpress

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: wpwp
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: hogehoge
    # env_file: .env
    volumes:
      - type: volume
        source: db-wordpress
        target: /var/lib/mysql
        volume:
          nocopy: true
    networks:
      - wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9001:80"
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wordpress

volumes:
  db-wordpress:
    external: true

networks:
  wordpress:
    external: true
