version: "3.7"
services:
  db:
    image: mysql:5.7
    container_name: wp-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    # env_file: .env
    volumes:
      - type: volume
        source: db-wordpress
        target: /var/lib/mysql
        volume:
          nocopy: true
      - ./db-wordpress/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
    networks:
      - wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp-pma
    ports:
      - "9001:80"
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: password
      VIRTUAL_HOST: wp-pma.localhost
      VIRTUAL_PORT: 80
    networks:
      - proxy
      - wordpress

volumes:
  db-wordpress:
    external: true

networks:
  proxy:
    external: true
  wordpress:
    external: true
